### ISSUE TITLE
Release of Dataset Generation Code 

### ISSUE THREAD

**Issue by manuelbrack** [ExplainableML/CLEVR-X#1]
Dear Authors, 

Are there any updates on when we can expect the release of the dataset generation code?. 
For our current research we would like to combine the textual explanations of CLEVR-X with the ground-truth for visual heatmaps presented in CLEVR-XAI ([https://github.com/ahmedmagdiosman/clevr-xai](url)). 
As CLEVR-XAI does not use the original CLEVR dataset, this requires generating new explanations. 

Any feedback from your side would be much appreciated. 

Cheers, 
Manuel Brack

**Comment by l-salewski** [comment]
Hey Manuel Brack,

thank you for taking interest in our work!

We are working on the release and I will try to provide an accurate ETA after the ECCV rebuttal deadline is over (this Sunday).


Best regards,
Leonard Salewski

**Comment by manuelbrack** [comment]
Hi, 

Thanks for the reply, that sounds great. 
I hope your rebuttal went well and I look forward to hearing from you.

Regards, 
Manuel Brack

**Comment by l-salewski** [comment]
Hi,

I just uploaded the CLEVR-X generation code and updated the readme with instructions on how to use it.
I will close the issue for now, feel free to open a new one if there are further issues.

Best regards,
Leonard Salewski
